/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class StereoCamera!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILESTEREOCAMERAINST

#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#include "OSGStereoCameraBase.h"
#include "OSGStereoCamera.h"



OSG_USING_NAMESPACE

#ifdef __sgi
#pragma set woff 1174
#endif

namespace
{
    static char cvsid_cpp       [] = "@(#)$Id: OSGStereoCameraBase.cpp,v 1.1 2002/05/24 15:50:49 fuenfzig Exp $";
    static char cvsid_hpp       [] = OSGSTEREOCAMERABASE_HEADER_CVSID;
    static char cvsid_inl       [] = OSGSTEREOCAMERABASE_INLINE_CVSID;

    static char cvsid_fields_hpp[] = OSGSTEREOCAMERAFIELDS_HEADER_CVSID;
}

#ifdef __sgi
#pragma reset woff 1174
#endif

const OSG::BitVector  StereoCameraBase::FovFieldMask = 
    (1 << StereoCameraBase::FovFieldId);

const OSG::BitVector  StereoCameraBase::EyedistanceFieldMask = 
    (1 << StereoCameraBase::EyedistanceFieldId);

const OSG::BitVector  StereoCameraBase::ZeroparallaxFieldMask = 
    (1 << StereoCameraBase::ZeroparallaxFieldId);

const OSG::BitVector  StereoCameraBase::WhicheyeFieldMask = 
    (1 << StereoCameraBase::WhicheyeFieldId);



// Field descriptions

/*! \var Real32          StereoCameraBase::_sfFov
    The vertical field of view, in radians.
*/
/*! \var Real32          StereoCameraBase::_sfEyedistance
    Eye distance
*/
/*! \var Real32          StereoCameraBase::_sfZeroparallax
    zero paralax
*/
/*! \var Real32          StereoCameraBase::_sfWhicheye
    0 left 1 right
*/
//! StereoCamera description

FieldDescription *StereoCameraBase::_desc[] = 
{
    new FieldDescription(SFReal32::getClassType(), 
                     "fov", 
                     FovFieldId, FovFieldMask,
                     false,
                     (FieldAccessMethod) &StereoCameraBase::getSFFov),
    new FieldDescription(SFReal32::getClassType(), 
                     "eyedistance", 
                     EyedistanceFieldId, EyedistanceFieldMask,
                     false,
                     (FieldAccessMethod) &StereoCameraBase::getSFEyedistance),
    new FieldDescription(SFReal32::getClassType(), 
                     "zeroparallax", 
                     ZeroparallaxFieldId, ZeroparallaxFieldMask,
                     false,
                     (FieldAccessMethod) &StereoCameraBase::getSFZeroparallax),
    new FieldDescription(SFReal32::getClassType(), 
                     "whicheye", 
                     WhicheyeFieldId, WhicheyeFieldMask,
                     false,
                     (FieldAccessMethod) &StereoCameraBase::getSFWhicheye)
};

//! StereoCamera type

FieldContainerType StereoCameraBase::_type(
    "StereoCamera",
    "Camera",
    NULL,
    (PrototypeCreateF) &StereoCameraBase::createEmpty,
    StereoCamera::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(StereoCameraBase, StereoCameraPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &StereoCameraBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &StereoCameraBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr StereoCameraBase::shallowCopy(void) const 
{ 
    StereoCameraPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const StereoCamera *>(this)); 

    return returnValue; 
}

UInt32 StereoCameraBase::getContainerSize(void) const 
{ 
    return sizeof(StereoCameraBase); 
}


void StereoCameraBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((StereoCameraBase *) &other, whichField);
}

/*------------------------- constructors ----------------------------------*/

//! Constructor

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

StereoCameraBase::StereoCameraBase(void) :
    _sfFov                    (), 
    _sfEyedistance            (), 
    _sfZeroparallax           (), 
    _sfWhicheye               (), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

//! Copy Constructor

StereoCameraBase::StereoCameraBase(const StereoCameraBase &source) :
    _sfFov                    (source._sfFov                    ), 
    _sfEyedistance            (source._sfEyedistance            ), 
    _sfZeroparallax           (source._sfZeroparallax           ), 
    _sfWhicheye               (source._sfWhicheye               ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

//! Destructor

StereoCameraBase::~StereoCameraBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 StereoCameraBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (FovFieldMask & whichField))
    {
        returnValue += _sfFov.getBinSize();
    }

    if(FieldBits::NoField != (EyedistanceFieldMask & whichField))
    {
        returnValue += _sfEyedistance.getBinSize();
    }

    if(FieldBits::NoField != (ZeroparallaxFieldMask & whichField))
    {
        returnValue += _sfZeroparallax.getBinSize();
    }

    if(FieldBits::NoField != (WhicheyeFieldMask & whichField))
    {
        returnValue += _sfWhicheye.getBinSize();
    }


    return returnValue;
}

void StereoCameraBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (FovFieldMask & whichField))
    {
        _sfFov.copyToBin(pMem);
    }

    if(FieldBits::NoField != (EyedistanceFieldMask & whichField))
    {
        _sfEyedistance.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ZeroparallaxFieldMask & whichField))
    {
        _sfZeroparallax.copyToBin(pMem);
    }

    if(FieldBits::NoField != (WhicheyeFieldMask & whichField))
    {
        _sfWhicheye.copyToBin(pMem);
    }


}

void StereoCameraBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (FovFieldMask & whichField))
    {
        _sfFov.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (EyedistanceFieldMask & whichField))
    {
        _sfEyedistance.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ZeroparallaxFieldMask & whichField))
    {
        _sfZeroparallax.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (WhicheyeFieldMask & whichField))
    {
        _sfWhicheye.copyFromBin(pMem);
    }


}

void StereoCameraBase::executeSyncImpl(      StereoCameraBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (FovFieldMask & whichField))
        _sfFov.syncWith(pOther->_sfFov);

    if(FieldBits::NoField != (EyedistanceFieldMask & whichField))
        _sfEyedistance.syncWith(pOther->_sfEyedistance);

    if(FieldBits::NoField != (ZeroparallaxFieldMask & whichField))
        _sfZeroparallax.syncWith(pOther->_sfZeroparallax);

    if(FieldBits::NoField != (WhicheyeFieldMask & whichField))
        _sfWhicheye.syncWith(pOther->_sfWhicheye);


}

