/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class DVRSimpleLUTShader!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILEDVRSIMPLELUTSHADERINST

#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#include "OSGDVRSimpleLUTShaderBase.h"
#include "OSGDVRSimpleLUTShader.h"


OSG_USING_NAMESPACE



//! DVRSimpleLUTShader type

FieldContainerType DVRSimpleLUTShaderBase::_type(
    "DVRSimpleLUTShader",
    "DVRSimpleShader",
    NULL,
    (PrototypeCreateF) &DVRSimpleLUTShaderBase::createEmpty,
    DVRSimpleLUTShader::initMethod,
    NULL,
    0);

//OSG_FIELD_CONTAINER_DEF(DVRSimpleLUTShaderBase, DVRSimpleLUTShaderPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &DVRSimpleLUTShaderBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &DVRSimpleLUTShaderBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr DVRSimpleLUTShaderBase::shallowCopy(void) const 
{ 
    DVRSimpleLUTShaderPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const DVRSimpleLUTShader *>(this)); 

    return returnValue; 
}

UInt32 DVRSimpleLUTShaderBase::getContainerSize(void) const 
{ 
    return sizeof(DVRSimpleLUTShader); 
}


void DVRSimpleLUTShaderBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((DVRSimpleLUTShaderBase *) &other, whichField);
}

/*------------------------- constructors ----------------------------------*/

//! Constructor

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

DVRSimpleLUTShaderBase::DVRSimpleLUTShaderBase(void) :
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

//! Copy Constructor

DVRSimpleLUTShaderBase::DVRSimpleLUTShaderBase(const DVRSimpleLUTShaderBase &source) :
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

//! Destructor

DVRSimpleLUTShaderBase::~DVRSimpleLUTShaderBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 DVRSimpleLUTShaderBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void DVRSimpleLUTShaderBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);


}

void DVRSimpleLUTShaderBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);


}

void DVRSimpleLUTShaderBase::executeSyncImpl(      DVRSimpleLUTShaderBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);


}



#include <OSGSFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

DataType FieldDataTraits<DVRSimpleLUTShaderPtr>::_type("DVRSimpleLUTShaderPtr", "DVRSimpleShaderPtr");

OSG_DLLEXPORT_SFIELD_DEF1(DVRSimpleLUTShaderPtr, OSG_VOLRENLIB_DLLTMPLMAPPING);

OSG_END_NAMESPACE


/*------------------------------------------------------------------------*/
/*                              cvs id's                                  */

#ifdef OSG_SGI_CC
#pragma set woff 1174
#endif

#ifdef OSG_LINUX_ICC
#pragma warning( disable : 177 )
#endif

namespace
{
    static Char8 cvsid_cpp       [] = "@(#)$Id: OSGDVRSimpleLUTShaderBase.cpp,v 1.1 2002/10/10 11:11:26 weiler Exp $";
    static Char8 cvsid_hpp       [] = OSGDVRSIMPLELUTSHADERBASE_HEADER_CVSID;
    static Char8 cvsid_inl       [] = OSGDVRSIMPLELUTSHADERBASE_INLINE_CVSID;

    static Char8 cvsid_fields_hpp[] = OSGDVRSIMPLELUTSHADERFIELDS_HEADER_CVSID;
}

