/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGDVRVOLUMEFIELDS_H_
#define _OSGDVRVOLUMEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OSGConfig.h>

#include <OSGFieldContainerPtr.h>
#include <OSGNodeCoreFieldDataType.h>
#include <OSGVolRenDef.h>

#include <OSGNodeCoreFields.h>

OSG_BEGIN_NAMESPACE

class DVRVolume;

//! DVRVolumePtr

typedef FCPtr<NodeCorePtr, DVRVolume> DVRVolumePtr;

/*! \brief DVRVolumePtr field traits 
    \ingroup FieldLib
*/

template <>
struct FieldDataTraits<DVRVolumePtr> : 
#ifdef MW_OSG_1_1
    public FieldTraitsRecurseMapper<DVRVolumePtr>
#else
    public FieldTraitsRecurseMapper<DVRVolumePtr, true>
#endif
{
    enum                        { StringConvertable = 0x00 };
    enum                        { bHasParent        = 0x01 };
};


OSG_END_NAMESPACE

#define OSGDVRVOLUMEFIELDS_HEADER_CVSID "@(#)$Id: OSGDVRVolumeFields.h,v 1.1 2002/10/10 11:11:26 weiler Exp $"

#endif /* _OSGDVRVOLUMEFIELDS_H_ */
