/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class DynamicSubdivisionLP!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILEDYNAMICSUBDIVISIONLPINST

#include <stdlib.h>
#include <stdio.h>
#include <OpenMesh/Core/Utils/Property.hh>

#include "OSGConfig.h"
#include "OSGDynamicSubdivisionLPBase.h"
#include "OSGDynamicSubdivisionLP.h"


OSG_USING_NAMESPACE

template <class MESH>
const OSG::BitVector  DynamicSubdivisionLPBase<MESH>::MinProjSizeFieldMask = 
    (1 << DynamicSubdivisionLPBase<MESH>::MinProjSizeFieldId);

template <class MESH>
const OSG::BitVector  DynamicSubdivisionLPBase<MESH>::MaxProjSizeFieldMask = 
    (1 << DynamicSubdivisionLPBase<MESH>::MaxProjSizeFieldId);

template <class MESH>
const OSG::BitVector  DynamicSubdivisionLPBase<MESH>::VertexClassifierFieldMask = 
    (1 << DynamicSubdivisionLPBase<MESH>::VertexClassifierFieldId);

template <class MESH>
const OSG::BitVector  DynamicSubdivisionLPBase<MESH>::NormalConeApertureFieldMask = 
    (1 << DynamicSubdivisionLPBase<MESH>::NormalConeApertureFieldId);

template <class MESH>
const OSG::BitVector  DynamicSubdivisionLPBase<MESH>::MinDepthFieldMask = 
    (1 << DynamicSubdivisionLPBase<MESH>::MinDepthFieldId);

template <class MESH>
const OSG::BitVector  DynamicSubdivisionLPBase<MESH>::MaxDepthFieldMask = 
    (1 << DynamicSubdivisionLPBase<MESH>::MaxDepthFieldId);

template <class MESH>
const OSG::BitVector  DynamicSubdivisionLPBase<MESH>::BackfaceCullingFieldMask = 
    (1 << DynamicSubdivisionLPBase<MESH>::BackfaceCullingFieldId);

template <class MESH>
const OSG::BitVector  DynamicSubdivisionLPBase<MESH>::MeshFieldMask = 
    (1 << DynamicSubdivisionLPBase<MESH>::MeshFieldId);

template <class MESH>
const OSG::BitVector  DynamicSubdivisionLPBase<MESH>::TesselatorFieldMask = 
    (1 << DynamicSubdivisionLPBase<MESH>::TesselatorFieldId);

template <class MESH>
const OSG::BitVector  DynamicSubdivisionLPBase<MESH>::AutoUpdateFieldMask = 
    (1 << DynamicSubdivisionLPBase<MESH>::AutoUpdateFieldId);



// Field descriptions

/*! \var Real32          DynamicSubdivisionCCBase::_sfMinProjSize
    minimum pixel size
*/
/*! \var Real32          DynamicSubdivisionCCBase::_sfMaxProjSize
    maximum pixel size
*/
/*! \var Real32          DynamicSubdivisionCCBase::_sfVertexClassifier
    silhouette epsilon
*/
/*! \var Real32          DynamicSubdivisionCCBase::_sfNormalConeAperture
    curvature calc. 
*/
/*! \var UInt16          DynamicSubdivisionLPBase::_sfMinDepth
    minimum subdivision depth
*/
/*! \var UInt16          DynamicSubdivisionLPBase::_sfMaxDepth
    maximum subdivision depth
*/
/*! \var bool            DynamicSubdivisionLPBase::_sfBackfaceCulling
    switch for backface culling
*/
/*! \var OpenMeshP       DynamicSubdivisionLPBase::_sfMesh
    base mesh used for subdivision
*/
/*! \var OpenMeshTesselatorP DynamicSubdivisionLPBase::_sfTesselator
    tesselator implementing the two-table algorithm
*/

//! DynamicSubdivisionLP description

template <class MESH>
FieldDescription *DynamicSubdivisionLPBase<MESH>::_desc[] = 
{
    new FieldDescription(SFReal32::getClassType(), 
                     "MinProjSize", 
                     MinProjSizeFieldId, MinProjSizeFieldMask,
                     false,
                     (FieldAccessMethod) &DynamicSubdivisionLPBase::getSFMinProjSize),
    new FieldDescription(SFReal32::getClassType(), 
                     "MaxProjSize", 
                     MaxProjSizeFieldId, MaxProjSizeFieldMask,
                     false,
                     (FieldAccessMethod) &DynamicSubdivisionLPBase::getSFMaxProjSize),
    new FieldDescription(SFReal32::getClassType(), 
                     "VertexClassifier", 
                     VertexClassifierFieldId, VertexClassifierFieldMask,
                     false,
                     (FieldAccessMethod) &DynamicSubdivisionLPBase::getSFVertexClassifier),
    new FieldDescription(SFReal32::getClassType(), 
                     "NormalConeAperture", 
                     NormalConeApertureFieldId, NormalConeApertureFieldMask,
                     false,
                     (FieldAccessMethod) &DynamicSubdivisionLPBase::getSFNormalConeAperture), 
    new FieldDescription(SFUInt16::getClassType(), 
                     "MinDepth", 
                     MinDepthFieldId, MinDepthFieldMask,
                     false,
                     (FieldAccessMethod) &DynamicSubdivisionLPBase::getSFMinDepth),
    new FieldDescription(SFUInt16::getClassType(), 
                     "MaxDepth", 
                     MaxDepthFieldId, MaxDepthFieldMask,
                     false,
                     (FieldAccessMethod) &DynamicSubdivisionLPBase::getSFMaxDepth),
    new FieldDescription(SFBool::getClassType(), 
                     "BackfaceCulling", 
                     BackfaceCullingFieldId, BackfaceCullingFieldMask,
                     false,
                     (FieldAccessMethod) &DynamicSubdivisionLPBase::getSFBackfaceCulling),
    new FieldDescription(SFOpenMeshP::getClassType(), 
                     "Mesh", 
                     MeshFieldId, MeshFieldMask,
                     false,
                     (FieldAccessMethod) &DynamicSubdivisionLPBase::getSFMesh),
    new FieldDescription(SFOpenMeshTesselatorP::getClassType(), 
                     "Tesselator", 
                     TesselatorFieldId, TesselatorFieldMask,
                     true,
                     (FieldAccessMethod) &DynamicSubdivisionLPBase::getSFTesselator),
    new FieldDescription(SFBool::getClassType(), 
                     "AutoUpdate", 
                     AutoUpdateFieldId, AutoUpdateFieldMask,
                     false,
                     (FieldAccessMethod) &DynamicSubdivisionLPBase::getSFAutoUpdate)
};


template <class MESH>
FieldContainerType DynamicSubdivisionLPBase<MESH>::_type(
    getName(),
    "Group",
    NULL,
    (PrototypeCreateF) &(DynamicSubdivisionLPBase<MESH>::createEmpty),
    DynamicSubdivisionLP<MESH>::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(DynamicSubdivisionLPBase, FCPtr<GroupPtr, DynamicSubdivisionLP<MESH> >)

/*------------------------------ get -----------------------------------*/

template <class MESH>
FieldContainerType &DynamicSubdivisionLPBase<MESH>::getType(void) 
{
    return _type; 
} 

template <class MESH>
const FieldContainerType &DynamicSubdivisionLPBase<MESH>::getType(void) const 
{
    return _type;
} 


template <class MESH>
FieldContainerPtr DynamicSubdivisionLPBase<MESH>::shallowCopy(void) const 
{ 
    FCPtr<GroupPtr, DynamicSubdivisionLP<MESH> > returnValue; 

    newPtr(returnValue, dynamic_cast<const DynamicSubdivisionLP<MESH>*>(this)); 

    return returnValue; 
}

template <class MESH>
UInt32 DynamicSubdivisionLPBase<MESH>::getContainerSize(void) const 
{ 
    return sizeof(DynamicSubdivisionLP<MESH>); 
}


template <class MESH>
void DynamicSubdivisionLPBase<MESH>::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((DynamicSubdivisionLPBase<MESH>*) &other, whichField);
}

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

template <class MESH>
DynamicSubdivisionLPBase<MESH>::DynamicSubdivisionLPBase(void) :
    _sfMinProjSize            (Real32(5.0)), 
    _sfMaxProjSize            (Real32(15.0)), 
    _sfVertexClassifier       (Real32(0.01)), 
    _sfNormalConeAperture     (Real32(0.01)), 
    _sfMinDepth               (UInt16(0)), 
    _sfMaxDepth               (UInt16(4)), 
    _sfBackfaceCulling        (bool(false)), 
    _sfMesh                   (OpenMeshP(NULL)), 
    _sfTesselator             (OpenMeshTesselatorP(NULL)),     
    _sfAutoUpdate             (bool(true)),     
    Inherited() 
{   
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

template <class MESH>
DynamicSubdivisionLPBase<MESH>::DynamicSubdivisionLPBase(const DynamicSubdivisionLPBase &source) :
    _sfMinProjSize            (source._sfMinProjSize            ), 
    _sfMaxProjSize            (source._sfMaxProjSize            ), 
    _sfVertexClassifier       (source._sfVertexClassifier       ), 
    _sfNormalConeAperture     (source._sfNormalConeAperture     ), 
    _sfMinDepth               (source._sfMinDepth               ), 
    _sfMaxDepth               (source._sfMaxDepth               ), 
    _sfBackfaceCulling        (source._sfBackfaceCulling        ), 
    _sfMesh                   (source._sfMesh                   ), 
    _sfTesselator             (source._sfTesselator             ),     
    _sfAutoUpdate             (source._sfAutoUpdate             ),     
    Inherited                 (source)
{   
}

/*-------------------------- destructors ----------------------------------*/

template <class MESH>
DynamicSubdivisionLPBase<MESH>::~DynamicSubdivisionLPBase(void)
{
}

/*------------------------------ access -----------------------------------*/

template <class MESH>
UInt32 DynamicSubdivisionLPBase<MESH>::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (MinProjSizeFieldMask & whichField))
    {
        returnValue += _sfMinProjSize.getBinSize();
    }

    if(FieldBits::NoField != (MaxProjSizeFieldMask & whichField))
    {
        returnValue += _sfMaxProjSize.getBinSize();
    }

    if(FieldBits::NoField != (VertexClassifierFieldMask & whichField))
    {
        returnValue += _sfVertexClassifier.getBinSize();
    }

    if(FieldBits::NoField != (NormalConeApertureFieldMask & whichField))
    {
        returnValue += _sfNormalConeAperture.getBinSize();
    }

    if(FieldBits::NoField != (MinDepthFieldMask & whichField))
    {
        returnValue += _sfMinDepth.getBinSize();
    }

    if(FieldBits::NoField != (MaxDepthFieldMask & whichField))
    {
        returnValue += _sfMaxDepth.getBinSize();
    }

    if(FieldBits::NoField != (BackfaceCullingFieldMask & whichField))
    {
        returnValue += _sfBackfaceCulling.getBinSize();
    }
    
#if 0
    if(FieldBits::NoField != (MeshFieldMask & whichField))
    {
        returnValue += _sfMesh.getBinSize();
    }

    if(FieldBits::NoField != (TesselatorFieldMask & whichField))
    {
        returnValue += _sfTesselator.getBinSize();
    }
#endif

    if(FieldBits::NoField != (AutoUpdateFieldMask & whichField))
    {
        returnValue += _sfAutoUpdate.getBinSize();
    }

    return returnValue;
}

template <class MESH>
void DynamicSubdivisionLPBase<MESH>::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (MinProjSizeFieldMask & whichField))
    {
        _sfMinProjSize.copyToBin(pMem);
    }

    if(FieldBits::NoField != (MaxProjSizeFieldMask & whichField))
    {
        _sfMaxProjSize.copyToBin(pMem);
    }

    if(FieldBits::NoField != (VertexClassifierFieldMask & whichField))
    {
        _sfVertexClassifier.copyToBin(pMem);
    }

    if(FieldBits::NoField != (NormalConeApertureFieldMask & whichField))
    {
        _sfNormalConeAperture.copyToBin(pMem);
    }

    if(FieldBits::NoField != (MinDepthFieldMask & whichField))
    {
        _sfMinDepth.copyToBin(pMem);
    }

    if(FieldBits::NoField != (MaxDepthFieldMask & whichField))
    {
        _sfMaxDepth.copyToBin(pMem);
    }

    if(FieldBits::NoField != (BackfaceCullingFieldMask & whichField))
    {
        _sfBackfaceCulling.copyToBin(pMem);
    }

    if(FieldBits::NoField != (MeshFieldMask & whichField))
    {
       // write openmesh
        //_sfMesh.copyToBin(pMem,*getMesh());       
       SINFO << "write Mesh" << std::endl;
       OSGMeshIO<MESH> myMeshIO(*getMesh());
       myMeshIO.writeOpenMesh(pMem);
       // fill limit points and normals to maxdepth
       getTesselator()->preprocessInstances();      
       
    }

#if 0
    if(FieldBits::NoField != (TesselatorFieldMask & whichField))
    {
        _sfTesselator.copyToBin(pMem);
    }
#endif

    if(FieldBits::NoField != (AutoUpdateFieldMask & whichField))
    {
        _sfAutoUpdate.copyToBin(pMem);
    }

}

template <class MESH>
void DynamicSubdivisionLPBase<MESH>::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (MinProjSizeFieldMask & whichField))
    {
        _sfMinProjSize.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (MaxProjSizeFieldMask & whichField))
    {
        _sfMaxProjSize.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (VertexClassifierFieldMask & whichField))
    {
        _sfVertexClassifier.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (NormalConeApertureFieldMask & whichField))
    {
        _sfNormalConeAperture.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (MinDepthFieldMask & whichField))
    {
        _sfMinDepth.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (MaxDepthFieldMask & whichField))
    {
        _sfMaxDepth.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (BackfaceCullingFieldMask & whichField))
    {
        _sfBackfaceCulling.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (MeshFieldMask & whichField))
    {
       // new OpenMesh object
       MESH* newmesh = new MESH;
       ::OpenMesh::EPropHandleT<Int32> isCrease;
       newmesh->add_property(isCrease,"isCrease");
       //_sfMesh.copyFromBin(pMem,getMesh());       
       SINFO << "read Mesh" << std::endl;
       OSGMeshIO<MESH> myMeshIO(*newmesh);
       myMeshIO.readOpenMesh(pMem);
       setMesh(newmesh);
    }

#if 0
    if(FieldBits::NoField != (TesselatorFieldMask & whichField))
    {
        _sfTesselator.copyFromBin(pMem);
    }
#endif

    if(FieldBits::NoField != (AutoUpdateFieldMask & whichField))
    {
        _sfAutoUpdate.copyFromBin(pMem);
    }

}

template <class MESH>
void DynamicSubdivisionLPBase<MESH>::executeSyncImpl(      DynamicSubdivisionLPBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (MinProjSizeFieldMask & whichField))
        _sfMinProjSize.syncWith(pOther->_sfMinProjSize);

    if(FieldBits::NoField != (MaxProjSizeFieldMask & whichField))
        _sfMaxProjSize.syncWith(pOther->_sfMaxProjSize);

    if(FieldBits::NoField != (VertexClassifierFieldMask & whichField))
        _sfVertexClassifier.syncWith(pOther->_sfVertexClassifier);

    if(FieldBits::NoField != (NormalConeApertureFieldMask & whichField))
        _sfNormalConeAperture.syncWith(pOther->_sfNormalConeAperture);

    if(FieldBits::NoField != (MinDepthFieldMask & whichField))
        _sfMinDepth.syncWith(pOther->_sfMinDepth);

    if(FieldBits::NoField != (MaxDepthFieldMask & whichField))
        _sfMaxDepth.syncWith(pOther->_sfMaxDepth);

    if(FieldBits::NoField != (BackfaceCullingFieldMask & whichField))
        _sfBackfaceCulling.syncWith(pOther->_sfBackfaceCulling);

    if(FieldBits::NoField != (MeshFieldMask & whichField))
        _sfMesh.syncWith(pOther->_sfMesh);

    if(FieldBits::NoField != (TesselatorFieldMask & whichField))
        _sfTesselator.syncWith(pOther->_sfTesselator);

    if(FieldBits::NoField != (AutoUpdateFieldMask & whichField))
        _sfAutoUpdate.syncWith(pOther->_sfAutoUpdate);


}


#ifndef FIELD_TYPE_DEF
#define FIELD_TYPE_DEF

#include "OSGSFieldTypeDef.inl"
#include "OSGMFieldTypeDef.inl"

#endif

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
template <class MESH>
DataType FieldDataTraits<FCPtr<GroupPtr, DynamicSubdivisionLP<MESH> > >::_type(getName(), "GroupPtr");

//OSG_DLLEXPORT_SFIELD_DEF1(FCPtr<GroupPtr, DynamicSubdivisionLP<MESH> >, OSG_SUBSURFACELIB_DLLMAPPING);
//OSG_DLLEXPORT_MFIELD_DEF1(FCPtr<GroupPtr, DynamicSubdivisionLP<MESH> >, OSG_SUBSURFACELIB_DLLMAPPING);
#endif

OSG_END_NAMESPACE


/*------------------------------------------------------------------------*/
/*                              cvs id's                                  */

#ifdef OSG_SGI_CC
#pragma set woff 1174
#endif

#ifdef OSG_LINUX_ICC
#pragma warning( disable : 177 )
#endif

#if 0
namespace
{
    static Char8 cvsid_cpp       [] = "@(#)$Id: OSGDynamicSubdivisionLPBase.cpp,v 1.7 2004/07/09 08:57:03 fuenfzig Exp $";
    static Char8 cvsid_hpp       [] = OSGDYNAMICSUBDIVISIONLPBASE_HEADER_CVSID;
    static Char8 cvsid_inl       [] = OSGDYNAMICSUBDIVISIONLPBASE_INLINE_CVSID;

    static Char8 cvsid_fields_hpp[] = OSGDYNAMICSUBDIVISIONLPFIELDS_HEADER_CVSID;
}
#endif
