/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ClusterWindowAtt
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCLUSTERWINDOWATTBASE_H_
#define _OSGCLUSTERWINDOWATTBASE_H_
#ifdef __sgi
#pragma once
#endif


#include <OSGConfig.h>
#include <OSGClusterDef.h>

#include <OSGBaseTypes.h>
#include <OSGFieldDescription.h>
#include <OSGFieldContainer.h>

#include <OSGAttachment.h> // Parent

#include <OSGUInt32Fields.h> // ServerId type
#include <OSGBoolFields.h> // Composite type
#include <OSGSFBaseTypes.h> // ImageTransType type
#include <OSGUInt32Fields.h> // SubTileSize type

#include <OSGClusterWindowAttFields.h>

OSG_BEGIN_NAMESPACE

class ClusterWindowAtt;
class BinaryDataHandler;

//! \brief ClusterWindowAtt Base Class.

class OSG_CLUSTERLIB_DLLMAPPING ClusterWindowAttBase : public Attachment
{
  private:

    typedef Attachment Inherited;

    /*==========================  PUBLIC  =================================*/
  public:

    enum
    {
        ServerIdFieldId       = Inherited::NextFieldId,
        CompositeFieldId      = ServerIdFieldId       + 1,
        ImageTransTypeFieldId = CompositeFieldId      + 1,
        SubTileSizeFieldId    = ImageTransTypeFieldId + 1,
        NextFieldId           = SubTileSizeFieldId    + 1
    };

    static const osg::BitVector ServerIdFieldMask;
    static const osg::BitVector CompositeFieldMask;
    static const osg::BitVector ImageTransTypeFieldMask;
    static const osg::BitVector SubTileSizeFieldMask;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static        FieldContainerType &getClassType    (void); 
    static        UInt32              getClassTypeId  (void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Get                                    */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType  (void); 
    virtual const FieldContainerType &getType  (void) const; 

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

    inline       SFUInt32            *getSFServerId       (void);
    inline       SFBool              *getSFComposite      (void);
    inline       SFString            *getSFImageTransType (void);
    inline       SFUInt32            *getSFSubTileSize    (void);

    inline       UInt32              &getServerId       (void);
    inline const UInt32              &getServerId       (void) const;
    inline       Bool                &getComposite      (void);
    inline const Bool                &getComposite      (void) const;
    inline       string              &getImageTransType (void);
    inline const string              &getImageTransType (void) const;
    inline       UInt32              &getSubTileSize    (void);
    inline const UInt32              &getSubTileSize    (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

    inline void setServerId       ( const UInt32 &value );
    inline void setComposite      ( const Bool &value );
    inline void setImageTransType ( const string &value );
    inline void setSubTileSize    ( const UInt32 &value );

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (const BitVector         &whichField);
    virtual void   copyToBin  (      BinaryDataHandler &pMem,
                               const BitVector         &whichField);
    virtual void   copyFromBin(      BinaryDataHandler &pMem,
                               const BitVector         &whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  ClusterWindowAttPtr      create          (void); 
    static  ClusterWindowAttPtr      createEmpty     (void); 

    /*! \}                                                                 */

    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerPtr     shallowCopy     (void) const; 

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/
  protected:

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFUInt32            _sfServerId;
    SFBool              _sfComposite;
    SFString            _sfImageTransType;
    SFUInt32            _sfSubTileSize;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    ClusterWindowAttBase(void);
    ClusterWindowAttBase(const ClusterWindowAttBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~ClusterWindowAttBase(void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    void executeSyncImpl(      ClusterWindowAttBase *pOther,
                         const BitVector         &whichField);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/
  private:

    friend class FieldContainer;

    static FieldDescription   *_desc[];
    static FieldContainerType  _type;


    // prohibit default functions (move to 'public' if you need one)
    void operator =(const ClusterWindowAttBase &source);
};

//---------------------------------------------------------------------------
//   Exported Types
//---------------------------------------------------------------------------


typedef ClusterWindowAttBase *ClusterWindowAttBaseP;

OSG_END_NAMESPACE

#define OSGCLUSTERWINDOWATTBASE_HEADER_CVSID "@(#)$Id: $"

#endif /* _OSGCLUSTERWINDOWATTBASE_H_ */
