/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ClusterWindowAtt!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILECLUSTERLIB
#define OSG_COMPILECLUSTERWINDOWATTINST

#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#include "OSGClusterWindowAttBase.h"
#include "OSGClusterWindowAtt.h"


OSG_BEGIN_NAMESPACE

DataType FieldDataTraits<ClusterWindowAttPtr>::_type("ClusterWindowAttPtr", true);

#if defined(__sgi)

#pragma instantiate SField<ClusterWindowAttPtr>::_fieldType
#pragma instantiate MField<ClusterWindowAttPtr>::_fieldType

#else

OSG_DLLEXPORT_DEF1(SField, ClusterWindowAttPtr, OSG_CLUSTERLIB_DLLTMPLMAPPING)
OSG_DLLEXPORT_DEF1(MField, ClusterWindowAttPtr, OSG_CLUSTERLIB_DLLTMPLMAPPING)

#endif

OSG_END_NAMESPACE

OSG_USING_NAMESPACE

#ifdef __sgi
#pragma set woff 1174
#endif

namespace
{
    static char cvsid_cpp       [] = "@(#)$Id: $";
    static char cvsid_hpp       [] = OSGCLUSTERWINDOWATTBASE_HEADER_CVSID;
    static char cvsid_inl       [] = OSGCLUSTERWINDOWATTBASE_INLINE_CVSID;

    static char cvsid_fields_hpp[] = OSGCLUSTERWINDOWATTFIELDS_HEADER_CVSID;
}

#ifdef __sgi
#pragma reset woff 1174
#endif

const OSG::BitVector	ClusterWindowAttBase::ServerIdFieldMask = 
    (1 << ClusterWindowAttBase::ServerIdFieldId);

const OSG::BitVector	ClusterWindowAttBase::XFieldMask = 
    (1 << ClusterWindowAttBase::XFieldId);

const OSG::BitVector	ClusterWindowAttBase::YFieldMask = 
    (1 << ClusterWindowAttBase::YFieldId);

const OSG::BitVector	ClusterWindowAttBase::CompositeFieldMask = 
    (1 << ClusterWindowAttBase::CompositeFieldId);



// Field descriptions

/*! \var UInt32          ClusterWindowAttBase::_sfServerId
    Which server is responsible for the attached Window
*/
/*! \var UInt32          ClusterWindowAttBase::_sfX
    X Position in client window
*/
/*! \var UInt32          ClusterWindowAttBase::_sfY
    Y Position in client window
*/
/*! \var Bool            ClusterWindowAttBase::_sfComposite
    Should the server send the rendered image back to the client
*/
//! ClusterWindowAtt description

FieldDescription *ClusterWindowAttBase::_desc[] = 
{
    new FieldDescription(SFUInt32::getClassType(), 
                     "serverId", 
                     ServerIdFieldId, ServerIdFieldMask,
                     false,
                     (FieldAccessMethod) &ClusterWindowAttBase::getSFServerId),
    new FieldDescription(SFUInt32::getClassType(), 
                     "x", 
                     XFieldId, XFieldMask,
                     false,
                     (FieldAccessMethod) &ClusterWindowAttBase::getSFX),
    new FieldDescription(SFUInt32::getClassType(), 
                     "y", 
                     YFieldId, YFieldMask,
                     false,
                     (FieldAccessMethod) &ClusterWindowAttBase::getSFY),
    new FieldDescription(SFBool::getClassType(), 
                     "composite", 
                     CompositeFieldId, CompositeFieldMask,
                     false,
                     (FieldAccessMethod) &ClusterWindowAttBase::getSFComposite)
};

//! ClusterWindowAtt type

FieldContainerType ClusterWindowAttBase::_type(
    "ClusterWindowAtt",
    "Attachment",
    NULL,
    (PrototypeCreateF) &ClusterWindowAttBase::createEmpty,
    ClusterWindowAtt::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(ClusterWindowAttBase, ClusterWindowAttPtr)

/*------------------------------ get -----------------------------------*/

static const char *getClassname(void)
{
    return "ClusterWindowAtt"; 
}

FieldContainerType &ClusterWindowAttBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &ClusterWindowAttBase::getType(void) const 
{
    return _type;
} 
/*! \}                                                                 */

FieldContainerPtr ClusterWindowAttBase::shallowCopy(void) const 
{ 
    ClusterWindowAttPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const ClusterWindowAtt *>(this)); 

    return returnValue; 
}

UInt32 ClusterWindowAttBase::getContainerSize(void) const 
{ 
    return sizeof(ClusterWindowAttBase); 
}


void ClusterWindowAttBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((ClusterWindowAttBase *) &other, whichField);
}

/*------------------------- constructors ----------------------------------*/

//! Constructor

ClusterWindowAttBase::ClusterWindowAttBase(void) :
	_sfServerId               (), 
	_sfX                      (), 
	_sfY                      (), 
	_sfComposite              (), 
	Inherited() 
{
}

//! Copy Constructor

ClusterWindowAttBase::ClusterWindowAttBase(const ClusterWindowAttBase &source) :
	_sfServerId               (source._sfServerId               ), 
	_sfX                      (source._sfX                      ), 
	_sfY                      (source._sfY                      ), 
	_sfComposite              (source._sfComposite              ), 
	Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

//! Destructor

ClusterWindowAttBase::~ClusterWindowAttBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 ClusterWindowAttBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ServerIdFieldMask & whichField))
    {
        returnValue += _sfServerId.getBinSize();
    }

    if(FieldBits::NoField != (XFieldMask & whichField))
    {
        returnValue += _sfX.getBinSize();
    }

    if(FieldBits::NoField != (YFieldMask & whichField))
    {
        returnValue += _sfY.getBinSize();
    }

    if(FieldBits::NoField != (CompositeFieldMask & whichField))
    {
        returnValue += _sfComposite.getBinSize();
    }


    return returnValue;
}

void ClusterWindowAttBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ServerIdFieldMask & whichField))
    {
        _sfServerId.copyToBin(pMem);
    }

    if(FieldBits::NoField != (XFieldMask & whichField))
    {
        _sfX.copyToBin(pMem);
    }

    if(FieldBits::NoField != (YFieldMask & whichField))
    {
        _sfY.copyToBin(pMem);
    }

    if(FieldBits::NoField != (CompositeFieldMask & whichField))
    {
        _sfComposite.copyToBin(pMem);
    }


}

void ClusterWindowAttBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ServerIdFieldMask & whichField))
    {
        _sfServerId.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (XFieldMask & whichField))
    {
        _sfX.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (YFieldMask & whichField))
    {
        _sfY.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (CompositeFieldMask & whichField))
    {
        _sfComposite.copyFromBin(pMem);
    }


}

void ClusterWindowAttBase::executeSyncImpl(      ClusterWindowAttBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (ServerIdFieldMask & whichField))
        _sfServerId.syncWith(pOther->_sfServerId);

    if(FieldBits::NoField != (XFieldMask & whichField))
        _sfX.syncWith(pOther->_sfX);

    if(FieldBits::NoField != (YFieldMask & whichField))
        _sfY.syncWith(pOther->_sfY);

    if(FieldBits::NoField != (CompositeFieldMask & whichField))
        _sfComposite.syncWith(pOther->_sfComposite);


}

