/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ClusterWindowAtt
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCLUSTERWINDOWATTBASE_H_
#define _OSGCLUSTERWINDOWATTBASE_H_
#ifdef __sgi
#pragma once
#endif


#include <OSGConfig.h>
#include <OSGClusterDef.h>

#include <OSGBaseTypes.h>
#include <OSGFieldDescription.h>
#include <OSGFieldContainer.h>

#include <OSGAttachment.h> // Parent

#include <OSGUInt32Fields.h> // ServerId type
#include <OSGUInt32Fields.h> // X type
#include <OSGUInt32Fields.h> // Y type
#include <OSGBoolFields.h> // Composite type

#include <OSGClusterWindowAttFields.h>

OSG_BEGIN_NAMESPACE

class ClusterWindowAtt;
class BinaryDataHandler;

/*! \brief ClusterWindowAtt Base Class. */

class OSG_CLUSTERLIB_DLLMAPPING ClusterWindowAttBase : public Attachment
{
  private:

    typedef Attachment Inherited;

    /*==========================  PUBLIC  =================================*/
  public:

    enum
    {
        ServerIdFieldId  = Inherited::NextFieldId,
        XFieldId         = ServerIdFieldId  + 1,
        YFieldId         = XFieldId         + 1,
        CompositeFieldId = YFieldId         + 1,
        NextFieldId      = CompositeFieldId + 1
    };

    static const osg::BitVector ServerIdFieldMask;
    static const osg::BitVector XFieldMask;
    static const osg::BitVector YFieldMask;
    static const osg::BitVector CompositeFieldMask;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static const  char               *getClassname(void);

    static        FieldContainerType &getClassType    (void); 
    static        UInt32              getClassTypeId  (void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Get                                    */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType  (void); 
    virtual const FieldContainerType &getType  (void) const; 

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

    inline       SFUInt32            *getSFServerId       (void);
    inline       SFUInt32            *getSFX              (void);
    inline       SFUInt32            *getSFY              (void);
    inline       SFBool              *getSFComposite      (void);

    inline       UInt32              &getServerId       (void);
    inline const UInt32              &getServerId       (void) const;
    inline       UInt32              &getX              (void);
    inline const UInt32              &getX              (void) const;
    inline       UInt32              &getY              (void);
    inline const UInt32              &getY              (void) const;
    inline       Bool                &getComposite      (void);
    inline const Bool                &getComposite      (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

    inline void setServerId       ( const UInt32 &value );
    inline void setX              ( const UInt32 &value );
    inline void setY              ( const UInt32 &value );
    inline void setComposite      ( const Bool &value );

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void         executeSync(      FieldContainer &other,
                                     const BitVector      &whichField);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32       getBinSize (const BitVector    &whichField);
    virtual void copyToBin  (      BinaryDataHandler &pMem,
                             const BitVector    &whichField);
    virtual void copyFromBin(      BinaryDataHandler &pMem,
                             const BitVector    &whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  ClusterWindowAttPtr    create          (void); 
    static  ClusterWindowAttPtr    createEmpty     (void); 

    /*! \}                                                                 */

    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerPtr     shallowCopy     (void) const; 

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/
  protected:

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFUInt32         	_sfServerId;
    SFUInt32         	_sfX;
    SFUInt32         	_sfY;
    SFBool           	_sfComposite;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    ClusterWindowAttBase(void);
    ClusterWindowAttBase(const ClusterWindowAttBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~ClusterWindowAttBase(void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    void executeSyncImpl(      ClusterWindowAttBase *pOther,
                         const BitVector         &whichField);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/
  private:

    friend class FieldContainer;

    static FieldDescription   *_desc[];
    static FieldContainerType  _type;


    // prohibit default functions (move to 'public' if you need one)

    void operator =(const ClusterWindowAtt &source);
};

//---------------------------------------------------------------------------
//   Exported Types
//---------------------------------------------------------------------------


typedef ClusterWindowAttBase *ClusterWindowAttBaseP;

OSG_END_NAMESPACE

#define OSGCLUSTERWINDOWATTBASE_HEADER_CVSID "@(#)$Id: $"

#endif /* _OSGCLUSTERWINDOWATTBASE_H_ */
