/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ClusterWindowAtt!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------


#define OSG_COMPILECLUSTERLIB
#define OSG_COMPILECLUSTERWINDOWATTINST

#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#include "OSGClusterWindowAttBase.h"
#include "OSGClusterWindowAtt.h"


OSG_USING_NAMESPACE

/***************************************************************************\
 *                               Types                                     *
\***************************************************************************/

OSG_BEGIN_NAMESPACE

DataType FieldDataTraits<ClusterWindowAttPtr>::_type("ClusterWindowAttPtr", true);

#if defined(__sgi)

#pragma instantiate SField<ClusterWindowAttPtr>::_fieldType
#pragma instantiate MField<ClusterWindowAttPtr>::_fieldType

#else

OSG_DLLEXPORT_DEF1(SField, ClusterWindowAttPtr, OSG_CLUSTERLIB_DLLTMPLMAPPING)
OSG_DLLEXPORT_DEF1(MField, ClusterWindowAttPtr, OSG_CLUSTERLIB_DLLTMPLMAPPING)

#endif

OSG_END_NAMESPACE

/***************************************************************************\
 *                           Class variables                               *
\***************************************************************************/

const OSG::BitVector	ClusterWindowAttBase::ServerIdFieldMask = 
    (1 << ClusterWindowAttBase::ServerIdFieldId);

const OSG::BitVector	ClusterWindowAttBase::CompositeFieldMask = 
    (1 << ClusterWindowAttBase::CompositeFieldId);



char ClusterWindowAttBase::cvsid[] = "@(#)$Id: $";

/** \brief Group field description
 */

FieldDescription *ClusterWindowAttBase::_desc[] = 
{
    new FieldDescription(SFUInt32::getClassType(), 
                     "serverId", 
                     ServerIdFieldId, ServerIdFieldMask,
                     false,
                     (FieldAccessMethod) &ClusterWindowAttBase::getSFServerId),
    new FieldDescription(SFBool::getClassType(), 
                     "composite", 
                     CompositeFieldId, CompositeFieldMask,
                     false,
                     (FieldAccessMethod) &ClusterWindowAttBase::getSFComposite)
};

/** \brief ClusterWindowAtt type
 */

FieldContainerType ClusterWindowAttBase::_type(
    "ClusterWindowAtt",
    "Attachment",
    NULL,
    (PrototypeCreateF) &ClusterWindowAttBase::createEmpty,
    ClusterWindowAtt::initMethod,
    _desc,
    sizeof(_desc));


/***************************************************************************\
 *                           Class methods                                 *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

/***************************************************************************\
 *                           Instance methods                              *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

//OSG_FIELD_CONTAINER_DEF(ClusterWindowAttBase, ClusterWindowAttPtr)

FieldContainerType &ClusterWindowAttBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &ClusterWindowAttBase::getType(void) const 
{
    return _type;
} 

FieldContainerPtr ClusterWindowAttBase::shallowCopy(void) const 
{ 
    ClusterWindowAttPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const ClusterWindowAtt *>(this)); 

    return returnValue; 
}

UInt32 ClusterWindowAttBase::getContainerSize(void) const 
{ 
    return sizeof(ClusterWindowAttBase); 
}


void ClusterWindowAttBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((ClusterWindowAttBase *) &other, whichField);
}

/*------------- constructors & destructors --------------------------------*/

/** \brief Constructor
 */

ClusterWindowAttBase::ClusterWindowAttBase(void) :
	_sfServerId	(), 
	_sfComposite	(), 
	Inherited() 
{
}

/** \brief Copy Constructor
 */

ClusterWindowAttBase::ClusterWindowAttBase(const ClusterWindowAttBase &source) :
	_sfServerId		(source._sfServerId), 
	_sfComposite		(source._sfComposite), 
	Inherited        (source)
{
}

/** \brief Destructor
 */

ClusterWindowAttBase::~ClusterWindowAttBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 ClusterWindowAttBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ServerIdFieldMask & whichField))
    {
        returnValue += _sfServerId.getBinSize();
    }

    if(FieldBits::NoField != (CompositeFieldMask & whichField))
    {
        returnValue += _sfComposite.getBinSize();
    }


    return returnValue;
}

MemoryHandle ClusterWindowAttBase::copyToBin(      MemoryHandle  pMem,
                                          const BitVector    &whichField)
{
    pMem = Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ServerIdFieldMask & whichField))
    {
        pMem = _sfServerId.copyToBin(pMem);
    }

    if(FieldBits::NoField != (CompositeFieldMask & whichField))
    {
        pMem = _sfComposite.copyToBin(pMem);
    }


    return pMem;
}

MemoryHandle ClusterWindowAttBase::copyFromBin(      MemoryHandle  pMem,
                                            const BitVector    &whichField)
{
    pMem = Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ServerIdFieldMask & whichField))
    {
        pMem = _sfServerId.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (CompositeFieldMask & whichField))
    {
        pMem = _sfComposite.copyFromBin(pMem);
    }


    return pMem;
}

/*------------------------------- dump ----------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/


void ClusterWindowAttBase::executeSyncImpl(      ClusterWindowAttBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (ServerIdFieldMask & whichField))
    {
        _sfServerId.syncWith(pOther->_sfServerId);
    }

    if(FieldBits::NoField != (CompositeFieldMask & whichField))
    {
        _sfComposite.syncWith(pOther->_sfComposite);
    }


}

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

