/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class FOXWindow!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILEWINDOWFOXINST

#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#include "OSGFOXWindowBase.h"
#include "OSGFOXWindow.h"


OSG_BEGIN_NAMESPACE

#ifdef WIN32
DataType FieldDataTraits<FOXWindowPtr>::_type("FOXWindowPtr", "WIN32WindowPtr");
#else
DataType FieldDataTraits<FOXWindowPtr>::_type("FOXWindowPtr", "XWindowPtr");
#endif

#if defined(__sgi)

#pragma instantiate SField<FOXWindowPtr>::_fieldType
#pragma instantiate MField<FOXWindowPtr>::_fieldType

#else

OSG_DLLEXPORT_SFIELD_DEF1(FOXWindowPtr, OSG_WINDOWFOXLIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(FOXWindowPtr, OSG_WINDOWFOXLIB_DLLTMPLMAPPING);
//OSG_DLLEXPORT_DEF1(SField, FOXWindowPtr, OSG_WINDOWFOXLIB_DLLTMPLMAPPING)
//OSG_DLLEXPORT_DEF1(MField, FOXWindowPtr, OSG_WINDOWFOXLIB_DLLTMPLMAPPING)

#endif

OSG_END_NAMESPACE


OSG_USING_NAMESPACE

#ifdef __sgi
#pragma set woff 1174
#endif

namespace
{
    static Char8 cvsid_cpp       [] = "@(#)$Id: OSGFOXWindowBase.cpp,v 1.1 2002/05/24 15:50:49 fuenfzig Exp $";
    static Char8 cvsid_hpp       [] = OSGFOXWINDOWBASE_HEADER_CVSID;
    static Char8 cvsid_inl       [] = OSGFOXWINDOWBASE_INLINE_CVSID;

    static Char8 cvsid_fields_hpp[] = OSGFOXWINDOWFIELDS_HEADER_CVSID;
}

#ifdef __sgi
#pragma reset woff 1174
#endif

const OSG::BitVector  FOXWindowBase::GlWidgetFieldMask = 
    (1 << FOXWindowBase::GlWidgetFieldId);



// Field descriptions

/*! \var FOXGLWidgetP    FOXWindowBase::_sfGlWidget
    GL canvas used for OpenSG rendering
*/

//! FOXWindow description

FieldDescription *FOXWindowBase::_desc[] = 
{
    new FieldDescription(SFFOXGLWidgetP::getClassType(), 
                     "glWidget", 
                     GlWidgetFieldId, GlWidgetFieldMask,
                     false,
                     (FieldAccessMethod) &FOXWindowBase::getSFGlWidget)
};

//! FOXWindow type

#ifdef WIN32
FieldContainerType FOXWindowBase::_type(
    "FOXWindow",
    "WIN32Window",
    NULL,
    (PrototypeCreateF) &FOXWindowBase::createEmpty,
    FOXWindow::initMethod,
    _desc,
    sizeof(_desc));
#else
FieldContainerType FOXWindowBase::_type(
    "FOXWindow",
    "XWindow",
    NULL,
    (PrototypeCreateF) &FOXWindowBase::createEmpty,
    FOXWindow::initMethod,
    _desc,
    sizeof(_desc));
#endif

//OSG_FIELD_CONTAINER_DEF(FOXWindowBase, FOXWindowPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &FOXWindowBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &FOXWindowBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr FOXWindowBase::shallowCopy(void) const 
{ 
    FOXWindowPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const FOXWindow *>(this)); 

    return returnValue; 
}

UInt32 FOXWindowBase::getContainerSize(void) const 
{ 
    return sizeof(FOXWindow); 
}


void FOXWindowBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((FOXWindowBase *) &other, whichField);
}

/*------------------------- constructors ----------------------------------*/

//! Constructor

FOXWindowBase::FOXWindowBase(void) :
    _sfGlWidget               (FOXGLWidgetP(NULL)), 
    Inherited() 
{
}

//! Copy Constructor

FOXWindowBase::FOXWindowBase(const FOXWindowBase &source) :
    _sfGlWidget               (source._sfGlWidget               ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

//! Destructor

FOXWindowBase::~FOXWindowBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 FOXWindowBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (GlWidgetFieldMask & whichField))
    {
        returnValue += _sfGlWidget.getBinSize();
    }


    return returnValue;
}

void FOXWindowBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (GlWidgetFieldMask & whichField))
    {
        _sfGlWidget.copyToBin(pMem);
    }


}

void FOXWindowBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (GlWidgetFieldMask & whichField))
    {
        _sfGlWidget.copyFromBin(pMem);
    }


}

void FOXWindowBase::executeSyncImpl(      FOXWindowBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (GlWidgetFieldMask & whichField))
        _sfGlWidget.syncWith(pOther->_sfGlWidget);


}
